# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 0 * * 0' # https://crontab.guru/

name: Build it

jobs:
  Build:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.2.2
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPO: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      # Installing quarto
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 0.3.71
    
      - name: Install packags and render
        run: |
          install2.r xml2 quarto
          quarto render README.qmd
    
      # There's an error with EndBug, need to use the safe.directory
      # option. More here
      # https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory
      - name: Dealing with GitConfig
        run: |
          git config --global --add safe.directory /__w/${GITHUB_REPO}/${GITHUB_REPO}
          
      - uses: EndBug/add-and-commit@v9
        with:
          add: README.md
  
  Post:
    runs-on: ubuntu-latest
    needs: Build
    container: rocker/tidyverse:4.2.2
    env:
      BSKY_PASS: ${{ secrets.BSKY_PASS }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.before }}
          fetch-depth: 0
      
      - name: Post it on BlueSky
        shell: bash
        run: |
          PASS=${{ env.BSKY_PASS }} make login
          make write_post
          make post

      
          
